#'ESM 262 assignment 4 Vazin
#' @title Fisheries Function
#' @description This function explores the revenues generated by fisheries catching multiple species of fish from different locations.
#' @param count values for the amount of each fish species caught per location
#' @param cost the price of each individual fish by species
#' @param graph- default is false, but if the user enters TRUE, will report graph of revenues by site with total revenue displayed
#' @return Returns for different sites; The most frequently caught species, revenues by site, and total fisheries revenue, results can be reported with or without a graphical representation of revenues  
#' @author Jasmine Vazin

fish_results <- function(count, price, graph = F){

#Calculate maximums by site 
site_1_yield <- count %>%
    dplyr::select(possible.fish, site_1) %>% 
    filter(site_1 == max(site_1)) %>% 
    melt(id.vars = "possible.fish")

site_2_yield <- count %>%
    dplyr::select(possible.fish, site_2) %>% 
    filter(site_2 == max(site_2)) %>% 
    melt(id.vars = "possible.fish")

site_3_yield <- count %>%
    dplyr::select(possible.fish, site_3) %>% 
    filter(site_3 == max(site_3)) %>% 
    melt(id.vars = "possible.fish")
  
#Create dataframe with the highest frequency fish   
max_fish <- rbind(site_1_yield, site_2_yield, site_3_yield) 

colnames(max_fish) <- c("Species", "Site", "Count")

#Calculate revenue by site and put it into a dataframe
site_revenue = data.frame(fish = possible.fish,
                       site1 = count[,2] * price[,2],
                       site2 = count[,3] * price[,2], 
                       site3 = count[,4] * price[,2])
 
site_revenue = melt(site_revenue, id = "fish")
  
colnames(site_revenue) <- c("fish", "Site", "Revenue")
  
#Add up total revenues by site
total_revenue <- site_revenue %>% 
    group_by(Site) %>% 
    summarise(total_revenue = sum(Revenue))
revenues <- as.data.frame(total_revenue)
  
#Calculate fisheries revenue total for all sites
Fisheries_Revenue = sum(total_revenue$total_revenue)
  
#Create graph of revenues by site
rev_graph <- ggplot(revenues, aes(x=Site, y=total_revenue))+
    geom_bar(stat = "identity", fill= "seagreen2")+
    annotate(geom="label", x=2, y=500, label= paste0("Total Fisheries Revenue For All Sites  " , "$",  Fisheries_Revenue),
    color="black", fill = "white")+
    xlab("Site")+
    ylab("Revenue (USD)")+
    labs(title = "Total Fishing Revenue By Site")+
  theme_dark()+
  theme(plot.title = element_text(hjust = 0.5))
   
  
#Returns if user wants a graph of revenues
  if(graph == T){
    
    return(list("Total Fisheries Revenue" = Fisheries_Revenue, "Highest Frequency Species Per Site" = max_fish,"Total Revenue By Site" = total_revenue, `Revenues By Site Graph` = rev_graph))
    
  }
  
#Returns with no graph
  else {
    
    return(list("Total Fisheries Revenue" = Fisheries_Revenue, "Species Yield By Site" = max_fish,"Total Revenue By Site" = total_revenue))
    
    
  }
  
}

